<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EmailLogsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('email_logs')->delete();
        
        \DB::table('email_logs')->insert(array (
            0 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:35:37',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 1,
                'message' => 'Hi Jacob, The Indy Platform has assigned Ticket #DA1-1 to you.',
                'morphable_id' => 1,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'j@indy.com',
                'updated_at' => '2022-12-19 00:35:37',
            ),
            1 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:35:39',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 2,
                'message' => 'Hi John, The Indy Platform has assigned Ticket #DA1-1 to you.',
                'morphable_id' => 2,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'j2@indy.com',
                'updated_at' => '2022-12-19 00:35:39',
            ),
            2 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:35:39',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 3,
                'message' => 'Hi Lisa, The Indy Platform has assigned Ticket #DA1-1 to you.',
                'morphable_id' => 3,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'l@indy.com',
                'updated_at' => '2022-12-19 00:35:39',
            ),
            3 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:35:40',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 4,
                'message' => 'Hi Bec, The Indy Platform has assigned Ticket #DA1-1 to you.',
                'morphable_id' => 4,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'b@indy.com',
                'updated_at' => '2022-12-19 00:35:40',
            ),
            4 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:36:52',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 5,
                'message' => 'Hi Jacob, The Indy Platform has assigned Ticket #DA1-2 to you.',
                'morphable_id' => 5,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'j@indy.com',
                'updated_at' => '2022-12-19 00:36:53',
            ),
            5 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:36:53',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 6,
                'message' => 'Hi John, The Indy Platform has assigned Ticket #DA1-2 to you.',
                'morphable_id' => 6,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'j2@indy.com',
                'updated_at' => '2022-12-19 00:36:53',
            ),
            6 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:36:54',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 7,
                'message' => 'Hi Lisa, The Indy Platform has assigned Ticket #DA1-2 to you.',
                'morphable_id' => 7,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'l@indy.com',
                'updated_at' => '2022-12-19 00:36:54',
            ),
            7 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:36:54',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 8,
                'message' => 'Hi Bec, The Indy Platform has assigned Ticket #DA1-2 to you.',
                'morphable_id' => 8,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'b@indy.com',
                'updated_at' => '2022-12-19 00:36:54',
            ),
            8 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:37:58',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 9,
                'message' => 'Hi John, The Indy Platform has assigned Ticket #DA1-3 to you.',
                'morphable_id' => 9,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'j2@indy.com',
                'updated_at' => '2022-12-19 00:37:58',
            ),
            9 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:38:00',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 10,
                'message' => 'Hi Bec, The Indy Platform has assigned Ticket #DA1-3 to you.',
                'morphable_id' => 10,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'b@indy.com',
                'updated_at' => '2022-12-19 00:38:00',
            ),
            10 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:38:54',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 11,
                'message' => 'Hi Lisa, The Indy Platform has assigned Ticket #DA1-4 to you.',
                'morphable_id' => 11,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'l@indy.com',
                'updated_at' => '2022-12-19 00:38:54',
            ),
            11 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:38:55',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 12,
                'message' => 'Hi Jacob, The Indy Platform has assigned Ticket #DA1-4 to you.',
                'morphable_id' => 12,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'j@indy.com',
                'updated_at' => '2022-12-19 00:38:55',
            ),
            12 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:38:55',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 13,
                'message' => 'Hi John, The Indy Platform has assigned Ticket #DA1-4 to you.',
                'morphable_id' => 13,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'j2@indy.com',
                'updated_at' => '2022-12-19 00:38:55',
            ),
            13 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:38:56',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 14,
                'message' => 'Hi Bec, The Indy Platform has assigned Ticket #DA1-4 to you.',
                'morphable_id' => 14,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'b@indy.com',
                'updated_at' => '2022-12-19 00:38:56',
            ),
            14 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:40:22',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 15,
                'message' => 'Hi Jacob, The Indy Platform has assigned Ticket #DA1-5 to you.',
                'morphable_id' => 15,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'j@indy.com',
                'updated_at' => '2022-12-19 00:40:22',
            ),
            15 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:40:24',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 16,
                'message' => 'Hi Lisa, The Indy Platform has assigned Ticket #DA1-5 to you.',
                'morphable_id' => 16,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'l@indy.com',
                'updated_at' => '2022-12-19 00:40:24',
            ),
            16 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:40:25',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 17,
                'message' => 'Hi John, The Indy Platform has assigned Ticket #DA1-5 to you.',
                'morphable_id' => 17,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'j2@indy.com',
                'updated_at' => '2022-12-19 00:40:25',
            ),
            17 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:40:26',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 18,
                'message' => 'Hi Bec, The Indy Platform has assigned Ticket #DA1-5 to you.',
                'morphable_id' => 18,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'b@indy.com',
                'updated_at' => '2022-12-19 00:40:26',
            ),
            18 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:42:50',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 19,
                'message' => 'Hi Jacob, The Indy Platform has assigned Ticket #DA1-6 to you.',
                'morphable_id' => 19,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'j@indy.com',
                'updated_at' => '2022-12-19 00:42:50',
            ),
            19 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:42:51',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 20,
                'message' => 'Hi John, The Indy Platform has assigned Ticket #DA1-6 to you.',
                'morphable_id' => 20,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'j2@indy.com',
                'updated_at' => '2022-12-19 00:42:51',
            ),
            20 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:42:51',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 21,
                'message' => 'Hi Lisa, The Indy Platform has assigned Ticket #DA1-6 to you.',
                'morphable_id' => 21,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'l@indy.com',
                'updated_at' => '2022-12-19 00:42:51',
            ),
            21 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:42:51',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 22,
                'message' => 'Hi Bec, The Indy Platform has assigned Ticket #DA1-6 to you.',
                'morphable_id' => 22,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'b@indy.com',
                'updated_at' => '2022-12-19 00:42:51',
            ),
            22 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:45:15',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 23,
                'message' => 'Hi Jacob, The Indy Platform has assigned Ticket #DA1-7 to you.',
                'morphable_id' => 23,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'j@indy.com',
                'updated_at' => '2022-12-19 00:45:15',
            ),
            23 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:45:15',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 24,
                'message' => 'Hi John, The Indy Platform has assigned Ticket #DA1-7 to you.',
                'morphable_id' => 24,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'j2@indy.com',
                'updated_at' => '2022-12-19 00:45:15',
            ),
            24 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:45:16',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 25,
                'message' => 'Hi Lisa, The Indy Platform has assigned Ticket #DA1-7 to you.',
                'morphable_id' => 25,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'l@indy.com',
                'updated_at' => '2022-12-19 00:45:16',
            ),
            25 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:45:16',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 26,
                'message' => 'Hi Bec, The Indy Platform has assigned Ticket #DA1-7 to you.',
                'morphable_id' => 26,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'b@indy.com',
                'updated_at' => '2022-12-19 00:45:16',
            ),
            26 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:46:56',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 27,
                'message' => 'Super Admin has posted a message in ticket # DA1-7',
                'morphable_id' => 1,
                'morphable_type' => 'App\\Models\\Tickets\\TicketNote',
                'status' => 'sent',
                'to' => 'demo',
                'updated_at' => '2022-12-19 00:46:56',
            ),
            27 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 00:47:02',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 28,
                'message' => 'Super Admin has posted a message in ticket # DA1-7',
                'morphable_id' => 2,
                'morphable_type' => 'App\\Models\\Tickets\\TicketNote',
                'status' => 'sent',
                'to' => 'demo',
                'updated_at' => '2022-12-19 00:47:02',
            ),
            28 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 22:25:22',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 29,
                'message' => 'Jacob has posted a message in ticket # DA1-6',
                'morphable_id' => 3,
                'morphable_type' => 'App\\Models\\Tickets\\TicketNote',
                'status' => 'sent',
                'to' => 'demo',
                'updated_at' => '2022-12-19 22:25:22',
            ),
            29 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 22:50:17',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 30,
                'message' => 'Bec has posted a message in ticket # DA1-4',
                'morphable_id' => 4,
                'morphable_type' => 'App\\Models\\Tickets\\TicketNote',
                'status' => 'sent',
                'to' => 'demo',
                'updated_at' => '2022-12-19 22:50:17',
            ),
            30 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 23:39:43',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 31,
                'message' => 'Ticket File Uploaded Email',
                'morphable_id' => 1,
                'morphable_type' => 'App\\Models\\Tickets\\ClientTicketFile',
                'status' => 'sent',
                'to' => 'b@indy.com',
                'updated_at' => '2022-12-19 23:39:43',
            ),
            31 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-19 23:39:52',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 32,
                'message' => 'John is requesting approval for a design in ticket # DA1-7',
                'morphable_id' => 1,
                'morphable_type' => 'App\\Models\\Tickets\\ClientTicketFile',
                'status' => 'sent',
                'to' => 'demo',
                'updated_at' => '2022-12-19 23:39:52',
            ),
            32 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-20 00:48:33',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 33,
                'message' => 'Ticket File Uploaded Email',
                'morphable_id' => 2,
                'morphable_type' => 'App\\Models\\Tickets\\ClientTicketFile',
                'status' => 'sent',
                'to' => 'b@indy.com',
                'updated_at' => '2022-12-20 00:48:33',
            ),
            33 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-20 00:48:38',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 34,
                'message' => 'Jacob is requesting approval for a design in ticket # DA1-1',
                'morphable_id' => 2,
                'morphable_type' => 'App\\Models\\Tickets\\ClientTicketFile',
                'status' => 'sent',
                'to' => 'demo',
                'updated_at' => '2022-12-20 00:48:38',
            ),
            34 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-20 04:29:55',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 35,
                'message' => 'Lisa has posted a message in ticket # DA1-5',
                'morphable_id' => 5,
                'morphable_type' => 'App\\Models\\Tickets\\TicketNote',
                'status' => 'sent',
                'to' => 'demo',
                'updated_at' => '2022-12-20 04:29:55',
            ),
            35 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-20 04:33:09',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 36,
                'message' => 'Hi Demo, wayne has created a printer job request #1.',
                'morphable_id' => 1,
                'morphable_type' => 'App\\Models\\PrinterJob',
                'status' => 'sent',
                'to' => 'demo',
                'updated_at' => '2022-12-20 04:33:10',
            ),
            36 => 
            array (
                'cc' => NULL,
                'created_at' => '2022-12-20 04:35:04',
                'deleted_at' => NULL,
                'failed_details' => NULL,
                'id' => 37,
                'message' => 'Hi John, The Indy Platform has assigned Ticket #DA1-8 to you.',
                'morphable_id' => 27,
                'morphable_type' => 'App\\Models\\Tickets\\TicketAssignee',
                'status' => 'sent',
                'to' => 'j2@indy.com',
                'updated_at' => '2022-12-20 04:35:04',
            ),
        ));
        
        
    }
}