<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TicketServicesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ticket_services')->delete();
        
        \DB::table('ticket_services')->insert(array (
            0 => 
            array (
                'created_at' => '2022-12-19 00:35:37',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => NULL,
                'id' => 1,
                'post_date' => NULL,
                'service_id' => 7,
                'ticket_id' => 1,
                'updated_at' => '2022-12-19 00:35:37',
                'updated_by' => NULL,
            ),
            1 => 
            array (
                'created_at' => '2022-12-19 00:35:37',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["DL", "A2", "POS"]',
                'id' => 2,
                'post_date' => NULL,
                'service_id' => 3,
                'ticket_id' => 1,
                'updated_at' => '2022-12-19 00:35:37',
                'updated_by' => NULL,
            ),
            2 => 
            array (
                'created_at' => '2022-12-19 00:35:39',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["Landscape", "MP4"]',
                'id' => 3,
                'post_date' => NULL,
                'service_id' => 2,
                'ticket_id' => 1,
                'updated_at' => '2022-12-19 00:35:39',
                'updated_by' => NULL,
            ),
            3 => 
            array (
                'created_at' => '2022-12-19 00:35:39',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["Homepage Header", "What\'s On"]',
                'id' => 4,
                'post_date' => NULL,
                'service_id' => 5,
                'ticket_id' => 1,
                'updated_at' => '2022-12-19 00:35:39',
                'updated_by' => NULL,
            ),
            4 => 
            array (
                'created_at' => '2022-12-19 00:35:40',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '[{"name": "Facebook Event", "quantity": "50"}, {"name": "Facebook Post", "quantity": null}, {"name": "Instagram", "quantity": "100"}]',
                'id' => 5,
                'post_date' => NULL,
                'service_id' => 4,
                'ticket_id' => 1,
                'updated_at' => '2022-12-19 00:35:40',
                'updated_by' => NULL,
            ),
            5 => 
            array (
                'created_at' => '2022-12-19 00:35:40',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '[{"name": "Pull Up Banner", "quantity": "2"}, {"name": "A4", "quantity": "3"}]',
                'id' => 6,
                'post_date' => NULL,
                'service_id' => 8,
                'ticket_id' => 1,
                'updated_at' => '2022-12-19 00:35:40',
                'updated_by' => NULL,
            ),
            6 => 
            array (
                'created_at' => '2022-12-19 00:36:52',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => NULL,
                'id' => 7,
                'post_date' => NULL,
                'service_id' => 7,
                'ticket_id' => 2,
                'updated_at' => '2022-12-19 00:36:52',
                'updated_by' => NULL,
            ),
            7 => 
            array (
                'created_at' => '2022-12-19 00:36:52',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["DL", "A3"]',
                'id' => 8,
                'post_date' => NULL,
                'service_id' => 3,
                'ticket_id' => 2,
                'updated_at' => '2022-12-19 00:36:52',
                'updated_by' => NULL,
            ),
            8 => 
            array (
                'created_at' => '2022-12-19 00:36:53',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["Portrait"]',
                'id' => 9,
                'post_date' => NULL,
                'service_id' => 2,
                'ticket_id' => 2,
                'updated_at' => '2022-12-19 00:36:53',
                'updated_by' => NULL,
            ),
            9 => 
            array (
                'created_at' => '2022-12-19 00:36:53',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["Homepage Header"]',
                'id' => 10,
                'post_date' => NULL,
                'service_id' => 5,
                'ticket_id' => 2,
                'updated_at' => '2022-12-19 00:36:53',
                'updated_by' => NULL,
            ),
            10 => 
            array (
                'created_at' => '2022-12-19 00:36:54',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '[{"name": "Facebook Post", "quantity": "400"}]',
                'id' => 11,
                'post_date' => NULL,
                'service_id' => 4,
                'ticket_id' => 2,
                'updated_at' => '2022-12-19 00:36:54',
                'updated_by' => NULL,
            ),
            11 => 
            array (
                'created_at' => '2022-12-19 00:36:54',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '[{"name": "A0", "quantity": "2"}, {"name": "Pull Up Banner", "quantity": "2"}]',
                'id' => 12,
                'post_date' => NULL,
                'service_id' => 8,
                'ticket_id' => 2,
                'updated_at' => '2022-12-19 00:36:54',
                'updated_by' => NULL,
            ),
            12 => 
            array (
                'created_at' => '2022-12-19 00:37:58',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["Portrait"]',
                'id' => 13,
                'post_date' => NULL,
                'service_id' => 2,
                'ticket_id' => 3,
                'updated_at' => '2022-12-19 00:37:58',
                'updated_by' => NULL,
            ),
            13 => 
            array (
                'created_at' => '2022-12-19 00:38:00',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '[{"name": "Instagram", "quantity": "0"}]',
                'id' => 14,
                'post_date' => NULL,
                'service_id' => 4,
                'ticket_id' => 3,
                'updated_at' => '2022-12-19 00:38:00',
                'updated_by' => NULL,
            ),
            14 => 
            array (
                'created_at' => '2022-12-19 00:38:54',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => NULL,
                'id' => 15,
                'post_date' => NULL,
                'service_id' => 7,
                'ticket_id' => 4,
                'updated_at' => '2022-12-19 00:38:54',
                'updated_by' => NULL,
            ),
            15 => 
            array (
                'created_at' => '2022-12-19 00:38:54',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["What\'s On"]',
                'id' => 16,
                'post_date' => NULL,
                'service_id' => 5,
                'ticket_id' => 4,
                'updated_at' => '2022-12-19 00:38:54',
                'updated_by' => NULL,
            ),
            16 => 
            array (
                'created_at' => '2022-12-19 00:38:55',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["A4", "Whats on Guide"]',
                'id' => 17,
                'post_date' => NULL,
                'service_id' => 3,
                'ticket_id' => 4,
                'updated_at' => '2022-12-19 00:38:55',
                'updated_by' => NULL,
            ),
            17 => 
            array (
                'created_at' => '2022-12-19 00:38:55',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["Portrait", "MP4"]',
                'id' => 18,
                'post_date' => NULL,
                'service_id' => 2,
                'ticket_id' => 4,
                'updated_at' => '2022-12-19 00:38:55',
                'updated_by' => NULL,
            ),
            18 => 
            array (
                'created_at' => '2022-12-19 00:38:56',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '[{"name": "Facebook Post", "quantity": "400"}]',
                'id' => 19,
                'post_date' => NULL,
                'service_id' => 4,
                'ticket_id' => 4,
                'updated_at' => '2022-12-19 00:38:56',
                'updated_by' => NULL,
            ),
            19 => 
            array (
                'created_at' => '2022-12-19 00:38:56',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '[{"name": "Blades Sign", "quantity": "40"}]',
                'id' => 20,
                'post_date' => NULL,
                'service_id' => 8,
                'ticket_id' => 4,
                'updated_at' => '2022-12-19 00:38:56',
                'updated_by' => NULL,
            ),
            20 => 
            array (
                'created_at' => '2022-12-19 00:40:22',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => NULL,
                'id' => 21,
                'post_date' => NULL,
                'service_id' => 7,
                'ticket_id' => 5,
                'updated_at' => '2022-12-19 00:40:22',
                'updated_by' => NULL,
            ),
            21 => 
            array (
                'created_at' => '2022-12-19 00:40:22',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["A3", "POS"]',
                'id' => 22,
                'post_date' => NULL,
                'service_id' => 3,
                'ticket_id' => 5,
                'updated_at' => '2022-12-19 00:40:22',
                'updated_by' => NULL,
            ),
            22 => 
            array (
                'created_at' => '2022-12-19 00:40:24',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["Homepage Header"]',
                'id' => 23,
                'post_date' => NULL,
                'service_id' => 5,
                'ticket_id' => 5,
                'updated_at' => '2022-12-19 00:40:24',
                'updated_by' => NULL,
            ),
            23 => 
            array (
                'created_at' => '2022-12-19 00:40:25',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["Portrait"]',
                'id' => 24,
                'post_date' => NULL,
                'service_id' => 2,
                'ticket_id' => 5,
                'updated_at' => '2022-12-19 00:40:25',
                'updated_by' => NULL,
            ),
            24 => 
            array (
                'created_at' => '2022-12-19 00:40:26',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '[{"name": "Facebook Post", "quantity": "0"}]',
                'id' => 25,
                'post_date' => NULL,
                'service_id' => 4,
                'ticket_id' => 5,
                'updated_at' => '2022-12-19 00:40:26',
                'updated_by' => NULL,
            ),
            25 => 
            array (
                'created_at' => '2022-12-19 00:40:26',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '[{"name": "Pull Up Banner", "quantity": "2"}]',
                'id' => 26,
                'post_date' => NULL,
                'service_id' => 8,
                'ticket_id' => 5,
                'updated_at' => '2022-12-19 00:40:26',
                'updated_by' => NULL,
            ),
            26 => 
            array (
                'created_at' => '2022-12-19 00:42:50',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => NULL,
                'id' => 27,
                'post_date' => NULL,
                'service_id' => 7,
                'ticket_id' => 6,
                'updated_at' => '2022-12-19 00:42:50',
                'updated_by' => NULL,
            ),
            27 => 
            array (
                'created_at' => '2022-12-19 00:42:50',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["DL", "A2", "Instagram"]',
                'id' => 28,
                'post_date' => NULL,
                'service_id' => 3,
                'ticket_id' => 6,
                'updated_at' => '2022-12-19 00:42:50',
                'updated_by' => NULL,
            ),
            28 => 
            array (
                'created_at' => '2022-12-19 00:42:51',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["Portrait", "Landscape"]',
                'id' => 29,
                'post_date' => NULL,
                'service_id' => 2,
                'ticket_id' => 6,
                'updated_at' => '2022-12-19 00:42:51',
                'updated_by' => NULL,
            ),
            29 => 
            array (
                'created_at' => '2022-12-19 00:42:51',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["Homepage Header"]',
                'id' => 30,
                'post_date' => NULL,
                'service_id' => 5,
                'ticket_id' => 6,
                'updated_at' => '2022-12-19 00:42:51',
                'updated_by' => NULL,
            ),
            30 => 
            array (
                'created_at' => '2022-12-19 00:42:51',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '[{"name": "Instagram", "quantity": "0"}]',
                'id' => 31,
                'post_date' => NULL,
                'service_id' => 4,
                'ticket_id' => 6,
                'updated_at' => '2022-12-19 00:42:51',
                'updated_by' => NULL,
            ),
            31 => 
            array (
                'created_at' => '2022-12-19 00:42:52',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '[{"name": "Pull Up Banner", "quantity": "2"}]',
                'id' => 32,
                'post_date' => NULL,
                'service_id' => 8,
                'ticket_id' => 6,
                'updated_at' => '2022-12-19 00:42:52',
                'updated_by' => NULL,
            ),
            32 => 
            array (
                'created_at' => '2022-12-19 00:45:15',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => NULL,
                'id' => 33,
                'post_date' => NULL,
                'service_id' => 7,
                'ticket_id' => 7,
                'updated_at' => '2022-12-19 00:45:15',
                'updated_by' => NULL,
            ),
            33 => 
            array (
                'created_at' => '2022-12-19 00:45:15',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["DL", "A3"]',
                'id' => 34,
                'post_date' => NULL,
                'service_id' => 3,
                'ticket_id' => 7,
                'updated_at' => '2022-12-19 00:45:15',
                'updated_by' => NULL,
            ),
            34 => 
            array (
                'created_at' => '2022-12-19 00:45:15',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["Portrait"]',
                'id' => 35,
                'post_date' => NULL,
                'service_id' => 2,
                'ticket_id' => 7,
                'updated_at' => '2022-12-19 00:45:15',
                'updated_by' => NULL,
            ),
            35 => 
            array (
                'created_at' => '2022-12-19 00:45:16',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '["Homepage Header"]',
                'id' => 36,
                'post_date' => NULL,
                'service_id' => 5,
                'ticket_id' => 7,
                'updated_at' => '2022-12-19 00:45:16',
                'updated_by' => NULL,
            ),
            36 => 
            array (
                'created_at' => '2022-12-19 00:45:16',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '[{"name": "Blades Sign", "quantity": "40"}]',
                'id' => 37,
                'post_date' => NULL,
                'service_id' => 8,
                'ticket_id' => 7,
                'updated_at' => '2022-12-19 00:45:16',
                'updated_by' => NULL,
            ),
            37 => 
            array (
                'created_at' => '2022-12-19 00:45:16',
                'created_by' => 7,
                'custom_fields' => NULL,
                'deleted_at' => NULL,
                'extras' => '[{"name": "Instagram", "quantity": "80"}]',
                'id' => 38,
                'post_date' => NULL,
                'service_id' => 4,
                'ticket_id' => 7,
                'updated_at' => '2022-12-19 00:45:16',
                'updated_by' => NULL,
            ),
        ));
        
        
    }
}