<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TicketAssigneesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('ticket_assignees')->delete();

        \DB::table('ticket_assignees')->insert([
            0 => [
                'admin_user_id' => 2,
                'created_at' => '2022-12-19 00:35:37',
                'created_by' => 1,
                'department_id' => 2,
                'id' => 1,
                'status' => 'open',
                'ticket_id' => 1,
                'updated_at' => '2022-12-19 00:35:37',
                'updated_by' => null,
            ],
            1 => [
                'admin_user_id' => 3,
                'created_at' => '2022-12-19 00:35:39',
                'created_by' => 1,
                'department_id' => 1,
                'id' => 2,
                'status' => 'open',
                'ticket_id' => 1,
                'updated_at' => '2022-12-19 00:35:39',
                'updated_by' => null,
            ],
            2 => [
                'admin_user_id' => 5,
                'created_at' => '2022-12-19 00:35:39',
                'created_by' => 1,
                'department_id' => 7,
                'id' => 3,
                'status' => 'open',
                'ticket_id' => 1,
                'updated_at' => '2022-12-19 00:35:39',
                'updated_by' => null,
            ],
            3 => [
                'admin_user_id' => 4,
                'created_at' => '2022-12-19 00:35:40',
                'created_by' => 1,
                'department_id' => 6,
                'id' => 4,
                'status' => 'open',
                'ticket_id' => 1,
                'updated_at' => '2022-12-19 00:35:40',
                'updated_by' => null,
            ],
            4 => [
                'admin_user_id' => 2,
                'created_at' => '2022-12-19 00:36:52',
                'created_by' => 1,
                'department_id' => 2,
                'id' => 5,
                'status' => 'open',
                'ticket_id' => 2,
                'updated_at' => '2022-12-19 00:36:52',
                'updated_by' => null,
            ],
            5 => [
                'admin_user_id' => 3,
                'created_at' => '2022-12-19 00:36:53',
                'created_by' => 1,
                'department_id' => 1,
                'id' => 6,
                'status' => 'open',
                'ticket_id' => 2,
                'updated_at' => '2022-12-19 00:36:53',
                'updated_by' => null,
            ],
            6 => [
                'admin_user_id' => 5,
                'created_at' => '2022-12-19 00:36:54',
                'created_by' => 1,
                'department_id' => 7,
                'id' => 7,
                'status' => 'open',
                'ticket_id' => 2,
                'updated_at' => '2022-12-19 00:36:54',
                'updated_by' => null,
            ],
            7 => [
                'admin_user_id' => 4,
                'created_at' => '2022-12-19 00:36:54',
                'created_by' => 1,
                'department_id' => 6,
                'id' => 8,
                'status' => 'open',
                'ticket_id' => 2,
                'updated_at' => '2022-12-19 00:36:54',
                'updated_by' => null,
            ],
            8 => [
                'admin_user_id' => 3,
                'created_at' => '2022-12-19 00:37:58',
                'created_by' => 1,
                'department_id' => 1,
                'id' => 9,
                'status' => 'open',
                'ticket_id' => 3,
                'updated_at' => '2022-12-19 00:37:58',
                'updated_by' => null,
            ],
            9 => [
                'admin_user_id' => 4,
                'created_at' => '2022-12-19 00:38:00',
                'created_by' => 1,
                'department_id' => 6,
                'id' => 10,
                'status' => 'open',
                'ticket_id' => 3,
                'updated_at' => '2022-12-19 00:38:00',
                'updated_by' => null,
            ],
            10 => [
                'admin_user_id' => 5,
                'created_at' => '2022-12-19 00:38:54',
                'created_by' => 1,
                'department_id' => 7,
                'id' => 11,
                'status' => 'open',
                'ticket_id' => 4,
                'updated_at' => '2022-12-19 00:38:54',
                'updated_by' => null,
            ],
            11 => [
                'admin_user_id' => 2,
                'created_at' => '2022-12-19 00:38:55',
                'created_by' => 1,
                'department_id' => 2,
                'id' => 12,
                'status' => 'open',
                'ticket_id' => 4,
                'updated_at' => '2022-12-19 00:38:55',
                'updated_by' => null,
            ],
            12 => [
                'admin_user_id' => 3,
                'created_at' => '2022-12-19 00:38:55',
                'created_by' => 1,
                'department_id' => 1,
                'id' => 13,
                'status' => 'open',
                'ticket_id' => 4,
                'updated_at' => '2022-12-19 00:38:55',
                'updated_by' => null,
            ],
            13 => [
                'admin_user_id' => 4,
                'created_at' => '2022-12-19 00:38:56',
                'created_by' => 1,
                'department_id' => 6,
                'id' => 14,
                'status' => 'open',
                'ticket_id' => 4,
                'updated_at' => '2022-12-19 00:38:56',
                'updated_by' => null,
            ],
            14 => [
                'admin_user_id' => 2,
                'created_at' => '2022-12-19 00:40:22',
                'created_by' => 1,
                'department_id' => 2,
                'id' => 15,
                'status' => 'open',
                'ticket_id' => 5,
                'updated_at' => '2022-12-19 00:40:22',
                'updated_by' => null,
            ],
            15 => [
                'admin_user_id' => 5,
                'created_at' => '2022-12-19 00:40:24',
                'created_by' => 1,
                'department_id' => 7,
                'id' => 16,
                'status' => 'open',
                'ticket_id' => 5,
                'updated_at' => '2022-12-19 00:40:24',
                'updated_by' => null,
            ],
            16 => [
                'admin_user_id' => 3,
                'created_at' => '2022-12-19 00:40:25',
                'created_by' => 1,
                'department_id' => 1,
                'id' => 17,
                'status' => 'open',
                'ticket_id' => 5,
                'updated_at' => '2022-12-19 00:40:25',
                'updated_by' => null,
            ],
            17 => [
                'admin_user_id' => 4,
                'created_at' => '2022-12-19 00:40:26',
                'created_by' => 1,
                'department_id' => 6,
                'id' => 18,
                'status' => 'open',
                'ticket_id' => 5,
                'updated_at' => '2022-12-19 00:40:26',
                'updated_by' => null,
            ],
            18 => [
                'admin_user_id' => 2,
                'created_at' => '2022-12-19 00:42:50',
                'created_by' => 1,
                'department_id' => 2,
                'id' => 19,
                'status' => 'open',
                'ticket_id' => 6,
                'updated_at' => '2022-12-19 00:42:50',
                'updated_by' => null,
            ],
            19 => [
                'admin_user_id' => 3,
                'created_at' => '2022-12-19 00:42:51',
                'created_by' => 1,
                'department_id' => 1,
                'id' => 20,
                'status' => 'open',
                'ticket_id' => 6,
                'updated_at' => '2022-12-19 00:42:51',
                'updated_by' => null,
            ],
            20 => [
                'admin_user_id' => 5,
                'created_at' => '2022-12-19 00:42:51',
                'created_by' => 1,
                'department_id' => 7,
                'id' => 21,
                'status' => 'open',
                'ticket_id' => 6,
                'updated_at' => '2022-12-19 00:42:51',
                'updated_by' => null,
            ],
            21 => [
                'admin_user_id' => 4,
                'created_at' => '2022-12-19 00:42:51',
                'created_by' => 1,
                'department_id' => 6,
                'id' => 22,
                'status' => 'open',
                'ticket_id' => 6,
                'updated_at' => '2022-12-19 00:42:51',
                'updated_by' => null,
            ],
            22 => [
                'admin_user_id' => 2,
                'created_at' => '2022-12-19 00:45:15',
                'created_by' => 1,
                'department_id' => 2,
                'id' => 23,
                'status' => 'open',
                'ticket_id' => 7,
                'updated_at' => '2022-12-19 00:45:15',
                'updated_by' => null,
            ],
            23 => [
                'admin_user_id' => 3,
                'created_at' => '2022-12-19 00:45:15',
                'created_by' => 1,
                'department_id' => 1,
                'id' => 24,
                'status' => 'open',
                'ticket_id' => 7,
                'updated_at' => '2022-12-19 00:45:15',
                'updated_by' => null,
            ],
            24 => [
                'admin_user_id' => 5,
                'created_at' => '2022-12-19 00:45:16',
                'created_by' => 1,
                'department_id' => 7,
                'id' => 25,
                'status' => 'open',
                'ticket_id' => 7,
                'updated_at' => '2022-12-19 00:45:16',
                'updated_by' => null,
            ],
            25 => [
                'admin_user_id' => 4,
                'created_at' => '2022-12-19 00:45:16',
                'created_by' => 1,
                'department_id' => 6,
                'id' => 26,
                'status' => 'open',
                'ticket_id' => 7,
                'updated_at' => '2022-12-19 00:45:16',
                'updated_by' => null,
            ],
            26 => [
                'admin_user_id' => 3,
                'created_at' => '2022-12-20 04:35:04',
                'created_by' => 1,
                'department_id' => 1,
                'id' => 27,
                'status' => 'open',
                'ticket_id' => 8,
                'updated_at' => '2022-12-20 04:35:04',
                'updated_by' => null,
            ],
        ]);
    }
}
