<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TicketServicesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('ticket_services')->delete();

        \DB::table('ticket_services')->insert([
            0 => [
                'created_at' => '2022-12-19 00:35:37',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => null,
                'id' => 1,
                'post_date' => null,
                'service_id' => 7,
                'ticket_id' => 1,
                'updated_at' => '2022-12-19 00:35:37',
                'updated_by' => null,
            ],
            1 => [
                'created_at' => '2022-12-19 00:35:37',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["DL", "A2", "POS"]',
                'id' => 2,
                'post_date' => null,
                'service_id' => 3,
                'ticket_id' => 1,
                'updated_at' => '2022-12-19 00:35:37',
                'updated_by' => null,
            ],
            2 => [
                'created_at' => '2022-12-19 00:35:39',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["Landscape", "MP4"]',
                'id' => 3,
                'post_date' => null,
                'service_id' => 2,
                'ticket_id' => 1,
                'updated_at' => '2022-12-19 00:35:39',
                'updated_by' => null,
            ],
            3 => [
                'created_at' => '2022-12-19 00:35:39',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["Homepage Header", "What\'s On"]',
                'id' => 4,
                'post_date' => null,
                'service_id' => 5,
                'ticket_id' => 1,
                'updated_at' => '2022-12-19 00:35:39',
                'updated_by' => null,
            ],
            4 => [
                'created_at' => '2022-12-19 00:35:40',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '[{"name": "Facebook Event", "quantity": "50"}, {"name": "Facebook Post", "quantity": null}, {"name": "Instagram", "quantity": "100"}]',
                'id' => 5,
                'post_date' => null,
                'service_id' => 4,
                'ticket_id' => 1,
                'updated_at' => '2022-12-19 00:35:40',
                'updated_by' => null,
            ],
            5 => [
                'created_at' => '2022-12-19 00:35:40',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '[{"name": "Pull Up Banner", "quantity": "2"}, {"name": "A4", "quantity": "3"}]',
                'id' => 6,
                'post_date' => null,
                'service_id' => 8,
                'ticket_id' => 1,
                'updated_at' => '2022-12-19 00:35:40',
                'updated_by' => null,
            ],
            6 => [
                'created_at' => '2022-12-19 00:36:52',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => null,
                'id' => 7,
                'post_date' => null,
                'service_id' => 7,
                'ticket_id' => 2,
                'updated_at' => '2022-12-19 00:36:52',
                'updated_by' => null,
            ],
            7 => [
                'created_at' => '2022-12-19 00:36:52',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["DL", "A3"]',
                'id' => 8,
                'post_date' => null,
                'service_id' => 3,
                'ticket_id' => 2,
                'updated_at' => '2022-12-19 00:36:52',
                'updated_by' => null,
            ],
            8 => [
                'created_at' => '2022-12-19 00:36:53',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["Portrait"]',
                'id' => 9,
                'post_date' => null,
                'service_id' => 2,
                'ticket_id' => 2,
                'updated_at' => '2022-12-19 00:36:53',
                'updated_by' => null,
            ],
            9 => [
                'created_at' => '2022-12-19 00:36:53',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["Homepage Header"]',
                'id' => 10,
                'post_date' => null,
                'service_id' => 5,
                'ticket_id' => 2,
                'updated_at' => '2022-12-19 00:36:53',
                'updated_by' => null,
            ],
            10 => [
                'created_at' => '2022-12-19 00:36:54',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '[{"name": "Facebook Post", "quantity": "400"}]',
                'id' => 11,
                'post_date' => null,
                'service_id' => 4,
                'ticket_id' => 2,
                'updated_at' => '2022-12-19 00:36:54',
                'updated_by' => null,
            ],
            11 => [
                'created_at' => '2022-12-19 00:36:54',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '[{"name": "A0", "quantity": "2"}, {"name": "Pull Up Banner", "quantity": "2"}]',
                'id' => 12,
                'post_date' => null,
                'service_id' => 8,
                'ticket_id' => 2,
                'updated_at' => '2022-12-19 00:36:54',
                'updated_by' => null,
            ],
            12 => [
                'created_at' => '2022-12-19 00:37:58',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["Portrait"]',
                'id' => 13,
                'post_date' => null,
                'service_id' => 2,
                'ticket_id' => 3,
                'updated_at' => '2022-12-19 00:37:58',
                'updated_by' => null,
            ],
            13 => [
                'created_at' => '2022-12-19 00:38:00',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '[{"name": "Instagram", "quantity": "0"}]',
                'id' => 14,
                'post_date' => null,
                'service_id' => 4,
                'ticket_id' => 3,
                'updated_at' => '2022-12-19 00:38:00',
                'updated_by' => null,
            ],
            14 => [
                'created_at' => '2022-12-19 00:38:54',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => null,
                'id' => 15,
                'post_date' => null,
                'service_id' => 7,
                'ticket_id' => 4,
                'updated_at' => '2022-12-19 00:38:54',
                'updated_by' => null,
            ],
            15 => [
                'created_at' => '2022-12-19 00:38:54',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["What\'s On"]',
                'id' => 16,
                'post_date' => null,
                'service_id' => 5,
                'ticket_id' => 4,
                'updated_at' => '2022-12-19 00:38:54',
                'updated_by' => null,
            ],
            16 => [
                'created_at' => '2022-12-19 00:38:55',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["A4", "Whats on Guide"]',
                'id' => 17,
                'post_date' => null,
                'service_id' => 3,
                'ticket_id' => 4,
                'updated_at' => '2022-12-19 00:38:55',
                'updated_by' => null,
            ],
            17 => [
                'created_at' => '2022-12-19 00:38:55',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["Portrait", "MP4"]',
                'id' => 18,
                'post_date' => null,
                'service_id' => 2,
                'ticket_id' => 4,
                'updated_at' => '2022-12-19 00:38:55',
                'updated_by' => null,
            ],
            18 => [
                'created_at' => '2022-12-19 00:38:56',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '[{"name": "Facebook Post", "quantity": "400"}]',
                'id' => 19,
                'post_date' => null,
                'service_id' => 4,
                'ticket_id' => 4,
                'updated_at' => '2022-12-19 00:38:56',
                'updated_by' => null,
            ],
            19 => [
                'created_at' => '2022-12-19 00:38:56',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '[{"name": "Blades Sign", "quantity": "40"}]',
                'id' => 20,
                'post_date' => null,
                'service_id' => 8,
                'ticket_id' => 4,
                'updated_at' => '2022-12-19 00:38:56',
                'updated_by' => null,
            ],
            20 => [
                'created_at' => '2022-12-19 00:40:22',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => null,
                'id' => 21,
                'post_date' => null,
                'service_id' => 7,
                'ticket_id' => 5,
                'updated_at' => '2022-12-19 00:40:22',
                'updated_by' => null,
            ],
            21 => [
                'created_at' => '2022-12-19 00:40:22',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["A3", "POS"]',
                'id' => 22,
                'post_date' => null,
                'service_id' => 3,
                'ticket_id' => 5,
                'updated_at' => '2022-12-19 00:40:22',
                'updated_by' => null,
            ],
            22 => [
                'created_at' => '2022-12-19 00:40:24',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["Homepage Header"]',
                'id' => 23,
                'post_date' => null,
                'service_id' => 5,
                'ticket_id' => 5,
                'updated_at' => '2022-12-19 00:40:24',
                'updated_by' => null,
            ],
            23 => [
                'created_at' => '2022-12-19 00:40:25',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["Portrait"]',
                'id' => 24,
                'post_date' => null,
                'service_id' => 2,
                'ticket_id' => 5,
                'updated_at' => '2022-12-19 00:40:25',
                'updated_by' => null,
            ],
            24 => [
                'created_at' => '2022-12-19 00:40:26',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '[{"name": "Facebook Post", "quantity": "0"}]',
                'id' => 25,
                'post_date' => null,
                'service_id' => 4,
                'ticket_id' => 5,
                'updated_at' => '2022-12-19 00:40:26',
                'updated_by' => null,
            ],
            25 => [
                'created_at' => '2022-12-19 00:40:26',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '[{"name": "Pull Up Banner", "quantity": "2"}]',
                'id' => 26,
                'post_date' => null,
                'service_id' => 8,
                'ticket_id' => 5,
                'updated_at' => '2022-12-19 00:40:26',
                'updated_by' => null,
            ],
            26 => [
                'created_at' => '2022-12-19 00:42:50',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => null,
                'id' => 27,
                'post_date' => null,
                'service_id' => 7,
                'ticket_id' => 6,
                'updated_at' => '2022-12-19 00:42:50',
                'updated_by' => null,
            ],
            27 => [
                'created_at' => '2022-12-19 00:42:50',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["DL", "A2", "Instagram"]',
                'id' => 28,
                'post_date' => null,
                'service_id' => 3,
                'ticket_id' => 6,
                'updated_at' => '2022-12-19 00:42:50',
                'updated_by' => null,
            ],
            28 => [
                'created_at' => '2022-12-19 00:42:51',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["Portrait", "Landscape"]',
                'id' => 29,
                'post_date' => null,
                'service_id' => 2,
                'ticket_id' => 6,
                'updated_at' => '2022-12-19 00:42:51',
                'updated_by' => null,
            ],
            29 => [
                'created_at' => '2022-12-19 00:42:51',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["Homepage Header"]',
                'id' => 30,
                'post_date' => null,
                'service_id' => 5,
                'ticket_id' => 6,
                'updated_at' => '2022-12-19 00:42:51',
                'updated_by' => null,
            ],
            30 => [
                'created_at' => '2022-12-19 00:42:51',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '[{"name": "Instagram", "quantity": "0"}]',
                'id' => 31,
                'post_date' => null,
                'service_id' => 4,
                'ticket_id' => 6,
                'updated_at' => '2022-12-19 00:42:51',
                'updated_by' => null,
            ],
            31 => [
                'created_at' => '2022-12-19 00:42:52',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '[{"name": "Pull Up Banner", "quantity": "2"}]',
                'id' => 32,
                'post_date' => null,
                'service_id' => 8,
                'ticket_id' => 6,
                'updated_at' => '2022-12-19 00:42:52',
                'updated_by' => null,
            ],
            32 => [
                'created_at' => '2022-12-19 00:45:15',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => null,
                'id' => 33,
                'post_date' => null,
                'service_id' => 7,
                'ticket_id' => 7,
                'updated_at' => '2022-12-19 00:45:15',
                'updated_by' => null,
            ],
            33 => [
                'created_at' => '2022-12-19 00:45:15',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["DL", "A3"]',
                'id' => 34,
                'post_date' => null,
                'service_id' => 3,
                'ticket_id' => 7,
                'updated_at' => '2022-12-19 00:45:15',
                'updated_by' => null,
            ],
            34 => [
                'created_at' => '2022-12-19 00:45:15',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["Portrait"]',
                'id' => 35,
                'post_date' => null,
                'service_id' => 2,
                'ticket_id' => 7,
                'updated_at' => '2022-12-19 00:45:15',
                'updated_by' => null,
            ],
            35 => [
                'created_at' => '2022-12-19 00:45:16',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '["Homepage Header"]',
                'id' => 36,
                'post_date' => null,
                'service_id' => 5,
                'ticket_id' => 7,
                'updated_at' => '2022-12-19 00:45:16',
                'updated_by' => null,
            ],
            36 => [
                'created_at' => '2022-12-19 00:45:16',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '[{"name": "Blades Sign", "quantity": "40"}]',
                'id' => 37,
                'post_date' => null,
                'service_id' => 8,
                'ticket_id' => 7,
                'updated_at' => '2022-12-19 00:45:16',
                'updated_by' => null,
            ],
            37 => [
                'created_at' => '2022-12-19 00:45:16',
                'created_by' => 7,
                'custom_fields' => null,
                'deleted_at' => null,
                'extras' => '[{"name": "Instagram", "quantity": "80"}]',
                'id' => 38,
                'post_date' => null,
                'service_id' => 4,
                'ticket_id' => 7,
                'updated_at' => '2022-12-19 00:45:16',
                'updated_by' => null,
            ],
        ]);
    }
}
