<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('users')->delete();

        \DB::table('users')->insert([
            0 => [
                'birth_date' => '1990-12-12 00:00:00',
                'contact_number' => '0',
                'created_at' => '2022-12-16 05:25:05',
                'deleted_at' => null,
                'display_in_dashboard' => 0,
                'email' => 'superadmin@indy.com.au',
                'email_verified_at' => null,
                'first_name' => 'Super Admin',
                'gender' => 'Male',
                'id' => 1,
                'last_name' => '',
                'middle_name' => '',
                'morphable_id' => 1,
                'morphable_type' => 'App\\Models\\Users\\AdminUser',
                'password' => '$2y$10$cGZ.FCnhH4vKBtstio5c2udT4t2HfPku5fCDW5z5Yw.aGLbJ5GG4G',
                'profile_file_id' => null,
                'remember_token' => null,
                'status' => 'active',
                'updated_at' => '2022-12-16 05:25:05',
            ],
            1 => [
                'birth_date' => null,
                'contact_number' => null,
                'created_at' => '2022-12-18 23:35:38',
                'deleted_at' => null,
                'display_in_dashboard' => 0,
                'email' => 'p@indy.com',
                'email_verified_at' => null,
                'first_name' => 'wayne',
                'gender' => null,
                'id' => 2,
                'last_name' => 'Printer Provider',
                'middle_name' => null,
                'morphable_id' => 1,
                'morphable_type' => 'App\\Models\\Printer',
                'password' => '$2y$10$OTRookVLNZDh7k8VGj6C..lMXwE2LX0p8rf/SmMYrT4qNcnWrlmCS',
                'profile_file_id' => null,
                'remember_token' => null,
                'status' => 'active',
                'updated_at' => '2022-12-18 23:35:38',
            ],
            2 => [
                'birth_date' => '2022-12-18 00:00:00',
                'contact_number' => null,
                'created_at' => '2022-12-18 23:37:09',
                'deleted_at' => null,
                'display_in_dashboard' => 0,
                'email' => 'j@indy.com',
                'email_verified_at' => null,
                'first_name' => 'Jacob',
                'gender' => null,
                'id' => 3,
                'last_name' => null,
                'middle_name' => null,
                'morphable_id' => 2,
                'morphable_type' => 'App\\Models\\Users\\AdminUser',
                'password' => '$2y$10$g3/9OFeNWMed.IgYBdxAJ.r3ER4ofGLzzzgeMTzj57GSDKWHfYgfa',
                'profile_file_id' => null,
                'remember_token' => null,
                'status' => 'active',
                'updated_at' => '2022-12-18 23:37:09',
            ],
            3 => [
                'birth_date' => '2022-12-18 00:00:00',
                'contact_number' => null,
                'created_at' => '2022-12-18 23:37:53',
                'deleted_at' => null,
                'display_in_dashboard' => 0,
                'email' => 'j2@indy.com',
                'email_verified_at' => null,
                'first_name' => 'John',
                'gender' => null,
                'id' => 4,
                'last_name' => null,
                'middle_name' => null,
                'morphable_id' => 3,
                'morphable_type' => 'App\\Models\\Users\\AdminUser',
                'password' => '$2y$10$dcOD7QmfX1OVXVTFRgc3tu0Oa/E0AU/7ztUvNalDxutM8U/3.Fvru',
                'profile_file_id' => null,
                'remember_token' => null,
                'status' => 'active',
                'updated_at' => '2022-12-18 23:37:53',
            ],
            4 => [
                'birth_date' => '2022-12-18 00:00:00',
                'contact_number' => null,
                'created_at' => '2022-12-18 23:38:39',
                'deleted_at' => null,
                'display_in_dashboard' => 0,
                'email' => 'b@indy.com',
                'email_verified_at' => null,
                'first_name' => 'Bec',
                'gender' => null,
                'id' => 5,
                'last_name' => null,
                'middle_name' => null,
                'morphable_id' => 4,
                'morphable_type' => 'App\\Models\\Users\\AdminUser',
                'password' => '$2y$10$HYvysc4mR2BdIiBp/yXpqOh2sfbtGvdl8q82tReesEoZ4q/duaQWS',
                'profile_file_id' => null,
                'remember_token' => null,
                'status' => 'active',
                'updated_at' => '2022-12-18 23:38:39',
            ],
            5 => [
                'birth_date' => '2022-12-18 00:00:00',
                'contact_number' => null,
                'created_at' => '2022-12-18 23:39:58',
                'deleted_at' => null,
                'display_in_dashboard' => 0,
                'email' => 'l@indy.com',
                'email_verified_at' => null,
                'first_name' => 'Lisa',
                'gender' => null,
                'id' => 6,
                'last_name' => null,
                'middle_name' => null,
                'morphable_id' => 5,
                'morphable_type' => 'App\\Models\\Users\\AdminUser',
                'password' => '$2y$10$eTA3yj2S9LH0dyJpepzZrukw9PBAL8IQ/6clKCp.xaaO/mPwpkW6.',
                'profile_file_id' => null,
                'remember_token' => null,
                'status' => 'active',
                'updated_at' => '2022-12-18 23:39:58',
            ],
            6 => [
                'birth_date' => '2022-12-19 00:00:00',
                'contact_number' => null,
                'created_at' => '2022-12-19 00:04:23',
                'deleted_at' => null,
                'display_in_dashboard' => 0,
                'email' => 'demo',
                'email_verified_at' => null,
                'first_name' => 'Demo',
                'gender' => null,
                'id' => 7,
                'last_name' => 'User',
                'middle_name' => null,
                'morphable_id' => 1,
                'morphable_type' => 'App\\Models\\Users\\ClientUser',
                'password' => '$2y$10$wHBhbE6AM2o6.t.dizV4JOJBPo92KWkb1xpsjPl2jJl6XyOLzxHFi',
                'profile_file_id' => null,
                'remember_token' => null,
                'status' => 'active',
                'updated_at' => '2022-12-19 00:04:23',
            ],
            7 => [
                'birth_date' => '2022-12-19 00:00:00',
                'contact_number' => null,
                'created_at' => '2022-12-19 03:15:47',
                'deleted_at' => null,
                'display_in_dashboard' => 0,
                'email' => 'd@indy.com',
                'email_verified_at' => null,
                'first_name' => 'Daniel',
                'gender' => null,
                'id' => 8,
                'last_name' => null,
                'middle_name' => null,
                'morphable_id' => 2,
                'morphable_type' => 'App\\Models\\Users\\ClientUser',
                'password' => '$2y$10$vTjcGiPHaPc4ngAFmmKzHeKN6bB4BdVTSPLjkRdyoU3uTE6kDtOGS',
                'profile_file_id' => null,
                'remember_token' => null,
                'status' => 'active',
                'updated_at' => '2022-12-19 03:15:47',
            ],
            8 => [
                'birth_date' => '2022-12-19 00:00:00',
                'contact_number' => null,
                'created_at' => '2022-12-19 03:16:12',
                'deleted_at' => null,
                'display_in_dashboard' => 0,
                'email' => 'w@indy.com',
                'email_verified_at' => null,
                'first_name' => 'Wayne',
                'gender' => null,
                'id' => 9,
                'last_name' => null,
                'middle_name' => null,
                'morphable_id' => 3,
                'morphable_type' => 'App\\Models\\Users\\ClientUser',
                'password' => '$2y$10$jhQcpSgzj.kYTxLTGqbNhuxtz2llE6YQQccioppbm799jC68kpzhi',
                'profile_file_id' => null,
                'remember_token' => null,
                'status' => 'active',
                'updated_at' => '2022-12-19 03:16:12',
            ],
            9 => [
                'birth_date' => '2022-12-19 00:00:00',
                'contact_number' => null,
                'created_at' => '2022-12-19 03:16:39',
                'deleted_at' => null,
                'display_in_dashboard' => 0,
                'email' => 'r@indy.com',
                'email_verified_at' => null,
                'first_name' => 'Ross',
                'gender' => null,
                'id' => 10,
                'last_name' => null,
                'middle_name' => null,
                'morphable_id' => 4,
                'morphable_type' => 'App\\Models\\Users\\ClientUser',
                'password' => '$2y$10$z6fk5DLusbK/36.Rmhtjsew4iLk3pKFe6wdVTPvVRKw0mAzFirrmu',
                'profile_file_id' => null,
                'remember_token' => null,
                'status' => 'active',
                'updated_at' => '2022-12-19 03:16:39',
            ],
        ]);
    }
}
